### PR TITLE
minimedia: Variable to disable FakeSensorServer

### PR DESCRIPTION
**Pull request by fredldotme**
Avoid instantiating the FakeSensorServer in case the
compile-time switch 'MINIMEDIA_SENSORSERVER_DISABLE' is set to 1.
This avoids conflicts between minimediaservice and the UBports
platform-api which results in working rotation support with
minimediaservice running in the Android container.

### CODE REVIEW

**Comment by abranson** [comment]
Hi,
Thanks for this. I'm wondering though if this is similar enough to the force_hal mechanism to work in the same way (line 50 in the spec). Does it need to be a runtime variable, or could it be compile time? Does Halium have a way of defining macros before the build like that? The force_hal thing is useful anyway, for devices that don't work well with HAL3.

If that's not possible, then this looks fine as it is.

**Comment by fredldotme** [comment]
Since we are building off the Android.mk we could add a compile-time switch there.
The droidmedia Makefile could check for the existance of a variable and define SENSORSERVER_DISABLE by itself.
TBF I haven't tried yet to set a variable from the device.mk and have it exposed in a module mk, but I could try.

**Comment by abranson** [comment]
That'd be great if you have chance to try. If it works for you then we could make a lot more of these device specific pieces configurable in a nice uniform way - and could even finally add Kimmoli's AudioPolicyService.

**Comment by fredldotme** [comment]
Updated the PR. This is now a compile-time switch which has to be set in the device's Makefile like this:

```
MINIMEDIA_SENSORSERVER_DISABLE := 1
```

**Pull request merged**
