### PR TITLE
start AudioPolicyService. MER#1550

### PR DESCRIPTION
**Pull request by kimmoli**

### CODE REVIEW

**Comment by foolab** [comment]
Why is that needed?

**Comment by kimmoli** [comment]
jolla-camera (or something through it) needs it after recording a video. Otherwise (on onyx) camera can not be started again. Logcat reports waiting for audio policy service.

**Comment by foolab** [comment]
The reason you mentioned needs to be added to the commit message.

I cannot merge that before I make sure it does not break Jolla phone, tablet and other HW so it will take some time ;-)

**Comment by kimmoli** [comment]
Improved commit message

**Comment by foolab** [comment]
Is there a reason why the service is needed only after we record the first video?

**Comment by kimmoli** [comment]
wild guess is that it has something to do with audio recording (and maybe recording start/stop sounds). 

And symptoms are a bit different in bacon @sledges @martinbrook dare to comment too?

17:20 < sledges> kimmoli: ah, in your case you can take video, in our case (hammerhead+bacon), camera freezes upong pressing "stop recording" button
17:21 < vgrade> sledges: bacon does not freeze anymore
17:22 < sledges> vgrade: it does here:)

**Comment by sledges** [comment]
17:28 < vgrade> <...> Then I got camera but froze on exit.  Then I added audio policy to minimedia, that fixed freeze.


Means I need to do a clean rebuild, and this patch shall work on my bacon too:)

**Comment by foolab** [comment]
We still do not have an answer to the question: Why it is needed. It is needed to cure a symptom but what is behind that symptom? Why does camera work for the first time?

**Comment by yacuken** [comment]
If I understand correctly AudioPolicyService control audio input/output stream activity/configuration.
But I don't have any idea why first video capture is work and what going on in camera hal library.

**Comment by saidinesh5** [comment]
We also use the patch in line 162: http://piratepad.net/hadk-faq-v2 to get camera up and running. Looks like the unpatched code there(without the commented out the camera sounds)  is something that would need audioservice too?

**Comment by krnlyng** [comment]
@abranson in the current hadk we have audioflingerglue as requirement for all devices in order to avoid the libcameraservice patch alltogether, but i am not sure if this is the same problem?

**Comment by sledges** [comment]
Sounds like this is the same case as it emits sound after video stops recording. Best to test out with the latest HADK, started audioflingerglue, and omitting camera shutter patches altogether (starting with line 34 in https://pastebin.com/SVW66jqz )

**Comment by kimmoli** [comment]
Make this optional.
Add android flag MINIMEDIA_AUDIOPOLICYSERVICE_ENABLE which will set CPPFLAG  AUDIOPOLICYSERVICE_ENABLE

ref - see #53

**Comment by mlehtima** [comment]
For future reference the usual way to enable AudioPolicyService after these changes is to add "MINIMEDIA_AUDIOPOLICYSERVICE_ENABLE := 1" to env.mk in droidmedia source folder.

**Pull request merged**
